config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('magazine.urls')),
    path('materials/', include('materials.urls', namespace='materials')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

magazine/urls.py
from django.urls import path
from magazine import views
from magazine import templatetags
from magazine.apps import MagazineConfig

# app_name = MagazineConfig.name

urlpatterns = [
    path('', views.AutocarListView.as_view(), name='home'),
    path('contacts/', views.contacts, name='contacts'),
    path('product/<int:pk>', views.AutocarDetailView.as_view(), name='product'),
    path('autocar_create/', views.AutocarCreateView.as_view(), name='autocar_create'),
    path('marka_create/', views.MarkaCreateView.as_view(), name='marka_create'),
    path('autocar_update/', views.AutocarUpdateView.as_view(), name='marka_update'),
]

# urlpatterns = [
#     path('', views.home, name='home'),
#     path('contacts/', views.contacts, name='contacts'),
#     path('product/<int:pk>', views.view_product, name='product'),
#     path('autocar_create/', views.autocar_create, name='autocar_create'),
#     path('marka_create/', views.marka_create, name='marka_create'),
# ]

materials/urls.py
from django.urls import path

from materials.apps import MaterialsConfig
from materials.views import (MaterialCreateView, MaterialListView, MaterialDetailView, MaterialUpdateView,
                             MaterialDeleteView, )

app_name = MaterialsConfig.name

urlpatterns = [
    path('create/', MaterialCreateView.as_view(), name='create'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>/', MaterialDetailView.as_view() , name='view'),
    path('edit/<int:pk>/', MaterialUpdateView.as_view() , name='edit'),
    path('delete/<int:pk>/', MaterialDeleteView.as_view(), name='delete'),
]

magazine/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Marka(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Autocar(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    image = models.ImageField(verbose_name='Изображение', upload_to='img/', **NULLABLE)
    marka = models.ForeignKey(Marka, verbose_name='Категория', on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='Цена', **NULLABLE)
    data_created = models.DateTimeField(verbose_name='Дата последнего изменения', auto_now_add=True)

    def __str__(self):
        return f"{self.marka}"

    class Meta:
        verbose_name = 'Автомобиль'
        verbose_name_plural = 'Автомобили'

materials/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Material(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    body = models.TextField(verbose_name='содержимое')

    views_count = models.IntegerField(default=0, verbose_name='Просмотры')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'материал'
        verbose_name_plural = 'материалы'

# class Material(models.Model):
#     title = models.CharField(max_length=100, verbose_name='Заголовок')
#     slug = models.CharField(max_length=100, verbose_name='slug')
#     text = models.TextField(verbose_name='Содержимое')
#     image = models.ImageField(upload_to='blog/', verbose_name='Изображeние', **NULLABLE)
#     created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
#     to_publish = models.BooleanField(default=True, verbose_name='Признак публикации')
#     views = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')

magazine/views.py
from django.shortcuts import render, get_object_or_404

import magazine
from magazine.models import Autocar, Marka
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, DetailView, CreateView, ListView, UpdateView, DeleteView


class AutocarCreateView(CreateView):
    model = Autocar
    fields = ('name', 'description', 'price', 'image', 'marka')
    success_url = reverse_lazy('home')


class AutocarListView(ListView):
    model = Autocar
    template_name = 'magazine/home.html'


# def home(request):
#     autocar_list = Autocar.objects.all()
#     context = {
#         'object_list': autocar_list
#     }
#     return render(request, 'magazine/home.html', context)


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'У вас новое сообщение от: {name} (телефон: {phone}): {message}')
    return render(request, 'magazine/contacts.html')


class AutocarDetailView(DetailView):
    model = Autocar


class AutocarUpdateView(UpdateView):
    model = Marka
    fields = ('name', 'description')
    success_url = reverse_lazy('home')


class MarkaUpdateView(UpdateView):
    model = Marka
    fields = ('name', 'description')
    success_url = reverse_lazy('home')


class AutocarDeleteView(DeleteView):
    model = Marka
    success_url = reverse_lazy('home')


class MarkaDeleteView(DeleteView):
    model = Marka
    success_url = reverse_lazy('home')


# def view_product(request, pk):
#     autocar_item = get_object_or_404(Autocar, pk=pk)
#     context = {
#         'object': autocar_item
#     }
#     return render(request, 'magazine/autocar_detail.html', {'product': Autocar.objects.get(pk=pk)})


#

class MarkaCreateView(CreateView):
    model = Marka
    fields = ('name', 'description')
    success_url = reverse_lazy('home')


# def marka_create(request):
#     if request.method == 'POST':
#         cat_name = request.POST.get('marka_name')
#         cat_desc = request.POST.get('marka_desc')
#         Marka.objects.create(name=marka_name, description=marka_desc)
#         return redirect('home')
#     return render(request, 'magazine/marka_form.html')


# def autocar_create(request):
#     if request.method == 'POST':
#         prod_category = request.POST.get('autocar_category')
#         name = request.POST.get('autocar_name')
#         price = request.POST.get('autocar_price')
#         description = request.POST.get('autocar_desc')
#         prod_image = request.FILES.get('autocar_image')
#         Autocar.objects.create(name=name, description=description, price=price,
#                                image=autocar_image, category=Marka.objects.get(id=autocar_category))
#         print(f"Данные:\n"
#               f"Название: {name}\n"
#               f"Описание: {description}\n"
#               f"Цена: {price}\n"
#               f"Фото: {autocar_image}\n"
#               f"Категория: {autocar_category}")
#     return render(request, 'magazine/autocar_form.html', {'autocar_create': Marka.objects.all()})

def toggle_active(request, slug):
    materials = get_object_or_404(magazine, slug=slug)
    if materials.to_publish:
        materials.to_publish = False
    else:
        materials.to_publish = True
    materials.save()
    return redirect('blog_detail', slug=materials.slug)

magazine/templates/magazine/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            Autocars
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Полезные ископаемые</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы верим</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

magazine/templates/magazine/includes/header.html
<!--<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">-->
<!--    <h5 class="my-0 mr-md-materials font-weight-normal">Даниэль Русский</h5>-->
<!--    <nav class="ms-5">-->
<!--        <a class="p-2 btn btn-outline-primary" href="{% url 'home' %}">Каталог</a>-->
<!--        <a class="p-2 btn btn-outline-primary" href="{% url 'contacts' %}">Контакты</a>-->
<!--    </nav>-->
<!--</div>-->

<!--<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-materials text-center">-->
<!--    <h1 class="display-4">Магазин</h1>-->

<!--</div>-->

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Даниэль Русский</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'home' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'contacts' %}">Контакты</a>
        <a class="p-2 btn btn-success" href="{% url 'marka_create' %}">Поиск марки</a>
        <a class="p-2 btn btn-primary" href="{% url 'autocar_create' %}">Поиск автомобиля</a>
        <a class="p-2 btn btn-outline-dark" href="{% url 'material_list' %}">Материалы</a>
    </nav>
</div>

magazine/templates/magazine/includes/inc_main_menu.html
<!--<div class="col-sm-4 offset-md-1 py-4">-->
<!--    <h4 class="text-white">Меню</h4>-->
<!--    <ul class="list-unstyled">-->
<!--        <li><a href="{% url 'main:index' %}" class="text-white">Главная</a></li>-->
<!--        <li><a href="{% url 'materials:list' %}" class="text-white">Материалы</a></li>-->
<!--        <li><a href="{% url 'main:contact' %}" class="text-white">Контакты</a></li>-->
<!--    </ul>-->
<!--</div>-->

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Даниэль Русский</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'home' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'contacts' %}">Контакты</a>
        <a class="p-2 btn btn-success" href="{% url 'marka_create' %}">Поиск марки</a>
        <a class="p-2 btn btn-primary" href="{% url 'autocar_create' %}">Поиск автомобиля</a>
        <a class="p-2 btn btn-outline-dark" href="{% url 'product' %}">Материалы</a>
    </nav>
</div>