config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('magazine.urls')),
    path('materials/', include('materials.urls', namespace='materials')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path

from materials.apps import MaterialsConfig
from materials.views import (MaterialCreateView, MaterialListView, MaterialDetailView, MaterialUpdateView,
                             MaterialDeleteView, )

app_name = MaterialsConfig.name

urlpatterns = [
    path('create/', MaterialCreateView.as_view(), name='create'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>/', MaterialDetailView.as_view() , name='view'),
    path('edit/<int:pk>/', MaterialUpdateView.as_view() , name='edit'),
    path('delete/<int:pk>/', MaterialDeleteView.as_view(), name='delete'),
]

materials/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Material(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    body = models.TextField(verbose_name='содержимое')

    views_count = models.IntegerField(default=0, verbose_name='Просмотры')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'материал'
        verbose_name_plural = 'материалы'

# class Material(models.Model):
#     title = models.CharField(max_length=100, verbose_name='Заголовок')
#     slug = models.CharField(max_length=100, verbose_name='slug')
#     text = models.TextField(verbose_name='Содержимое')
#     image = models.ImageField(upload_to='blog/', verbose_name='Изображeние', **NULLABLE)
#     created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
#     to_publish = models.BooleanField(default=True, verbose_name='Признак публикации')
#     views = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')

materials/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from materials.models import Material
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify


class MaterialCreateView(CreateView):
    model = Material
    fields = ('title', 'body',)
    success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
            return super().form_valid(form)


class MaterialUpdateView(UpdateView):
    model = Material
    fields = ('title', 'body',)
    # success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slugify(new_mat.title)
            new_mat.save()
            return super().form_valid(form)

    def get_success_url(self):
        return reverse('materials:view', args=[self.kwargs.get('pk')])


class MaterialListView(ListView):
    model = Material

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published = True)
        return queryset


class MaterialDeleteView(DeleteView):
    model = Material
    success_url = reverse_lazy('materials:list')


class MaterialDetailView(DetailView):
    model = Material
    success_url = reverse_lazy('product')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

materials/templates/materials/material_confirm_delete.html
{% extends 'magazine/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить материал? "{{ object.title }}"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'materials:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/material_detail.html
{% extends 'magazine/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Материал "{{ object|title }}" ({{ object.slug }})
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.body }}
                    </p>
                </div>
                <div class="card-footer">Просмотры : {{ object.views_count }}</div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
            

materials/templates/materials/material_form.html
{% extends 'magazine/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

materials/templates/materials/material_list.html
{% extends 'magazine/base.html' %}
{% block content %}

<div class="row">
    <a class="btn btn-outline-primary" href="{% url 'materials:create' %}">Добавить материалы</a>
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">

            <div class="card-body">
                <p class="card-text">
                    {{ object|title }}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'materials:view' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">View</a>
                        <a href="{% url 'materials:edit' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Edit</a>
                        <a href="{% url 'materials:delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}